### PR TITLE
Change version to PHP 7.0; Change libpng12 to libpng-dev;

### PR DESCRIPTION
**Pull request by markwylde**
This makes the docker-compose build the images, however it still doesn't make the docker-compose work.

### CODE REVIEW

**Comment by fcoelho** [comment]
Thanks for the contribution!

I'm going to merge the first commit, though not the first one. If unzip is trying to replace files, I'm assuming that something went wrong at some point and I'd like to avoid automatic removal of those files, see #1 too

**Comment by fcoelho** [comment]
Or now with the new change I'll just squash it :)

**Comment by markwylde** [comment]
Awesome. Yeah you are right, I have removed the `-o` as it was just me running all those services at one.

**Comment by fcoelho** [comment]
Merged in a7920ead4e41c6af02dc3771f29a81a289d150e6, thanks again!

**Pull request closed without merging**
